MODE 7
REM -------DEFINITIONS-------
BL$=CHR$(255)      :REM BLOCK
NBL$=" "           :REM NO BLOCK
B$=CHR$(8)         :REM CURSOR BACK
F$=CHR$(9)         :REM CURSOR FORWARD
D$=CHR$(10)        :REM CURSOR DOWN
U$=CHR$(11)        :REM CURSOR UP
DIM SET$(3)        :REM SETS CHARACTER BLOCK 
DIM NSET$(3)       :REM SETS THE NEGATIVE OF CHARACTER BLOCK
DIM SETHB$(3,3,3)  :REM DEFINES SET BLOCKS HIT BOX
DIM SCREEN$(14,21) :REM SCREEN ARRAY SIZE
X=0 : Y=0 : R=0 : COL=FALSE : THISREMOVEDLINE%=0 :REM PLAYER X,Y,R / COLLISION / CURSOR LINE REMOVE  
SCORE%=0 : AMSER=0 : LEAVE=FALSE : START=FALSE   :REM SCORE / TIME / LEAVE / START
SETAMSER=20                                      :REM SET CLOCK TICK RATE
REM -------COLOUR-DEFINITIONS-------
L$=CHR$(141) : ST$=CHR$(137) : G$=CHR$(130) :REM L$-GRAPHIC/ ST$-TEXT / G$-GREEN
Y$=CHR$(131) : BL$=CHR$(132) : M$=CHR$(133) :REM Y$-YELLOW / BL$-BLUE / M$-MAGENTA
C$=CHR$(134) : FL$=CHR$(136) : R$=CHR$(129) :REM C$-CYAN   /FL$-BLINK / R$-RED
DIM CL$(17)  :REM COLOUR SET 
REM -------ARENA-WALLS-N-CLS-NEXT-BLOCK-------
FOR YA=0 TO 21 : SCREEN$(11,YA)=BL$ : NEXT YA
FOR XA=0 TO 10 : SCREEN$(XA,18)=BL$ : NEXT XA
FOR SCL=0 TO 4  : CL$(SCL)=G$ : NEXT SCL
FOR SCL=5 TO 8  : CL$(SCL)=Y$ : NEXT SCL
FOR SCL=9 TO 12 : CL$(SCL)=BL$: NEXT SCL
FOR SCL=13 TO 17: CL$(SCL)=M$ : NEXT SCL 
NIT$=NBL$+NBL$+NBL$+NBL$+D$+B$+B$+B$+B$+NBL$+NBL$+NBL$+NBL$+D$+B$+B$+B$+B$+NBL$+NBL$+NBL$+NBL$+D$+B$+B$+B$+B$+NBL$+NBL$+NBL$+NBL$
REM -------BLOCK-DEFINITIONS-------
DIM OBA$(3) :REM O BLOCK
OBA$(0)=BL$+BL$+D$+B$+B$+BL$+BL$
OBA$(1)=BL$+BL$+D$+B$+B$+BL$+BL$             :REM LOOP 01
OBA$(2)=BL$+BL$+D$+B$+B$+BL$+BL$             :REM LOOP 02
OBA$(3)=BL$+BL$+D$+B$+B$+BL$+BL$             :REM LOOP 03
DIM IBA$(3) :REM I BLOCK
IBA$(0)=BL$+D$+B$+BL$+D$+B$+BL$+D$+B$+BL$
IBA$(1)=BL$+BL$+BL$+BL$
IBA$(2)=BL$+D$+B$+BL$+D$+B$+BL$+D$+B$+BL$    :REM LOOP 01
IBA$(3)=BL$+BL$+BL$+BL$                      :REM LOOP 02
DIM SBA$(3) :REM S BLOCK
SBA$(0)=F$+BL$+BL$+D$+B$+B$+B$+BL$+BL$+F$
SBA$(1)=BL$+D$+B$+BL$+BL$+D$+B$+BL$
SBA$(2)=F$+BL$+BL$+D$+B$+B$+B$+BL$+BL$+F$    :REM LOOP 01
SBA$(3)=BL$+D$+B$+BL$+BL$+D$+B$+BL$          :REM LOOP 02
DIM ZBA$(3) :REM Z BLOCK
ZBA$(0)=BL$+BL$+D$+B$+B$+F$+BL$+BL$
ZBA$(1)=F$+BL$+D$+B$+B$+BL$+BL$+D$+B$+B$+BL$
ZBA$(2)=BL$+BL$+D$+B$+B$+F$+BL$+BL$          :REM LOOP 01
ZBA$(3)=F$+BL$+D$+B$+B$+BL$+BL$+D$+B$+B$+BL$ :REM LOOP 02
DIM LBA$(3) :REM L BLOCK
LBA$(0)=BL$+D$+B$+BL$+D$+B$+BL$+BL$
LBA$(1)=BL$+BL$+BL$+D$+B$+B$+B$+BL$
LBA$(2)=BL$+BL$+D$+B$+BL$+D$+B$+BL$
LBA$(3)=F$+F$+BL$+D$+B$+B$+B$+BL$+BL$+BL$
DIM JBA$(3) :REM J BLOCK
JBA$(0)=F$+BL$+D$+B$+BL$+D$+B$+B$+BL$+BL$
JBA$(1)=BL$+D$+B$+BL$+BL$+BL$
JBA$(2)=BL$+BL$+D$+B$+B$+BL$+D$+B$+BL$
JBA$(3)=BL$+BL$+BL$+D$+B$+BL$
DIM TBA$(3) :REM T BLOCK
TBA$(0)=BL$+BL$+BL$+D$+B$+B$+BL$
TBA$(1)=F$+BL$+D$+B$+B$+BL$+BL$+D$+B$+BL$
TBA$(2)=F$+BL$+D$+B$+B$+BL$+BL$+BL$
TBA$(3)=BL$+D$+B$+BL$+BL$+D$+B$+B$+BL$
PRINT"GRAPHIC BLOCKS DEFINED"
REM -------EMPTY-BLOCK-DEFINITIONS-------
DIM EOBA$(3) :REM EMPTY O BLOCK
EOBA$(0)=NBL$+NBL$+D$+B$+B$+NBL$+NBL$
EOBA$(1)=NBL$+NBL$+D$+B$+B$+NBL$+NBL$             :REM LOOP 01
EOBA$(2)=NBL$+NBL$+D$+B$+B$+NBL$+NBL$             :REM LOOP 02
EOBA$(3)=NBL$+NBL$+D$+B$+B$+NBL$+NBL$             :REM LOOP 03
DIM EIBA$(3) :REM EMPTY I BLOCK
EIBA$(0)=NBL$+D$+B$+NBL$+D$+B$+NBL$+D$+B$+NBL$
EIBA$(1)=NBL$+NBL$+NBL$+NBL$
EIBA$(2)=NBL$+D$+B$+NBL$+D$+B$+NBL$+D$+B$+NBL$    :REM LOOP 01
EIBA$(3)=NBL$+NBL$+NBL$+NBL$                      :REM LOOP 02
DIM ESBA$(3) :REM EMPTY S BLOCK
ESBA$(0)=F$+NBL$+NBL$+D$+B$+B$+B$+NBL$+NBL$+F$
ESBA$(1)=NBL$+D$+B$+NBL$+NBL$+D$+B$+NBL$
ESBA$(2)=F$+NBL$+NBL$+D$+B$+B$+B$+NBL$+NBL$+F$    :REM LOOP 01
ESBA$(3)=NBL$+D$+B$+NBL$+NBL$+D$+B$+NBL$          :REM LOOP 02
DIM EZBA$(3) :REM EMPTY Z BLOCK
EZBA$(0)=NBL$+NBL$+D$+B$+B$+F$+NBL$+NBL$
EZBA$(1)=F$+NBL$+D$+B$+B$+NBL$+NBL$+D$+B$+B$+NBL$
EZBA$(2)=NBL$+NBL$+D$+B$+B$+F$+NBL$+NBL$          :REM LOOP 01
EZBA$(3)=F$+NBL$+D$+B$+B$+NBL$+NBL$+D$+B$+B$+NBL$ :REM LOOP 02
DIM ELBA$(3) :REM EMPTY L BLOCK
ELBA$(0)=NBL$+D$+B$+NBL$+D$+B$+NBL$+NBL$
ELBA$(1)=NBL$+NBL$+NBL$+D$+B$+B$+B$+NBL$
ELBA$(2)=NBL$+NBL$+D$+B$+NBL$+D$+B$+NBL$
ELBA$(3)=F$+F$+NBL$+D$+B$+B$+B$+NBL$+NBL$+NBL$
DIM EJBA$(3) :REM EMPTY J BLOCK
EJBA$(0)=F$+NBL$+D$+B$+NBL$+D$+B$+B$+NBL$+NBL$
EJBA$(1)=NBL$+D$+B$+NBL$+NBL$+NBL$
EJBA$(2)=NBL$+NBL$+D$+B$+B$+NBL$+D$+B$+NBL$
EJBA$(3)=NBL$+NBL$+NBL$+D$+B$+NBL$
DIM ETBA$(3) :REM EMPTY T BLOCK
ETBA$(0)=NBL$+NBL$+NBL$+D$+B$+B$+NBL$
ETBA$(1)=F$+NBL$+D$+B$+B$+NBL$+NBL$+D$+B$+NBL$
ETBA$(2)=F$+NBL$+D$+B$+B$+NBL$+NBL$+NBL$
ETBA$(3)=NBL$+D$+B$+NBL$+NBL$+D$+B$+B$+NBL$
PRINT"EMPTY GRAPHIC BLOCKS DEFINED"
REM -------HITBOX-DEFINITIONS-------
OBAH$(0,0,0)=BL$ :OBAH$(0,1,0)=BL$ :OBAH$(0,0,1)=BL$ :OBAH$(0,1,1)=BL$
OBAH$(1,0,0)=BL$ :OBAH$(1,1,0)=BL$ :OBAH$(1,0,1)=BL$ :OBAH$(1,1,1)=BL$  :REM LOOP 01
OBAH$(2,0,0)=BL$ :OBAH$(2,1,0)=BL$ :OBAH$(2,0,1)=BL$ :OBAH$(2,1,1)=BL$  :REM LOOP 02
OBAH$(3,0,0)=BL$ :OBAH$(3,1,0)=BL$ :OBAH$(3,0,1)=BL$ :OBAH$(3,1,1)=BL$  :REM LOOP 03
DIM IBAH$(3,3,3) :REM I BLOCK HIT BOX
IBAH$(0,0,0)=BL$ :IBAH$(0,0,1)=BL$ :IBAH$(0,0,2)=BL$ :IBAH$(0,0,3)=BL$
IBAH$(1,0,0)=BL$ :IBAH$(1,1,0)=BL$ :IBAH$(1,2,0)=BL$ :IBAH$(1,3,0)=BL$
IBAH$(2,0,0)=BL$ :IBAH$(2,0,1)=BL$ :IBAH$(2,0,2)=BL$ :IBAH$(2,0,3)=BL$  :REM LOOP 01
IBAH$(3,0,0)=BL$ :IBAH$(3,1,0)=BL$ :IBAH$(3,2,0)=BL$ :IBAH$(3,3,0)=BL$  :REM LOOP 02
DIM SBAH$(3,3,3) :REM S BLOCK HIT BOX
SBAH$(0,1,0)=BL$ :SBAH$(0,2,0)=BL$ :SBAH$(0,0,1)=BL$ :SBAH$(0,1,1)=BL$
SBAH$(1,0,0)=BL$ :SBAH$(1,0,1)=BL$ :SBAH$(1,1,1)=BL$ :SBAH$(1,1,2)=BL$
SBAH$(2,1,0)=BL$ :SBAH$(2,2,0)=BL$ :SBAH$(2,0,1)=BL$ :SBAH$(2,1,1)=BL$  :REM LOOP 01
SBAH$(3,0,0)=BL$ :SBAH$(3,0,1)=BL$ :SBAH$(3,1,1)=BL$ :SBAH$(3,1,2)=BL$  :REM LOOP 02
DIM ZBAH$(3,3,3) :REM Z BLOCK HIT BOX
ZBAH$(0,0,0)=BL$ :ZBAH$(0,1,0)=BL$ :ZBAH$(0,1,1)=BL$ :ZBAH$(0,2,1)=BL$
ZBAH$(1,1,0)=BL$ :ZBAH$(1,0,1)=BL$ :ZBAH$(1,1,1)=BL$ :ZBAH$(1,0,2)=BL$
ZBAH$(2,0,0)=BL$ :ZBAH$(2,1,0)=BL$ :ZBAH$(2,1,1)=BL$ :ZBAH$(2,2,1)=BL$  :REM LOOP 01
ZBAH$(3,1,0)=BL$ :ZBAH$(3,0,1)=BL$ :ZBAH$(3,1,1)=BL$ :ZBAH$(3,0,2)=BL$  :REM LOOP 02
DIM LBAH$(3,3,3) :REM L BLOCK HIT BOX
LBAH$(0,0,0)=BL$ :LBAH$(0,0,1)=BL$ :LBAH$(0,0,2)=BL$ :LBAH$(0,1,2)=BL$
LBAH$(1,0,0)=BL$ :LBAH$(1,1,0)=BL$ :LBAH$(1,2,0)=BL$ :LBAH$(1,0,1)=BL$
LBAH$(2,0,0)=BL$ :LBAH$(2,1,0)=BL$ :LBAH$(2,1,1)=BL$ :LBAH$(2,1,2)=BL$
LBAH$(3,2,0)=BL$ :LBAH$(3,0,1)=BL$ :LBAH$(3,1,1)=BL$ :LBAH$(3,2,1)=BL$
DIM JBAH$(3,3,3) :REM J BLOCK HIT BOX
JBAH$(0,1,0)=BL$ :JBAH$(0,1,1)=BL$ :JBAH$(0,0,2)=BL$ :JBAH$(0,1,2)=BL$
JBAH$(1,0,0)=BL$ :JBAH$(1,0,1)=BL$ :JBAH$(1,1,1)=BL$ :JBAH$(1,2,1)=BL$
JBAH$(2,0,0)=BL$ :JBAH$(2,1,0)=BL$ :JBAH$(2,0,1)=BL$ :JBAH$(2,0,2)=BL$
JBAH$(3,0,0)=BL$ :JBAH$(3,1,0)=BL$ :JBAH$(3,2,0)=BL$ :JBAH$(3,2,1)=BL$
DIM TBAH$(3,3,3) :REM T BLOCK HIT BOX
TBAH$(0,0,0)=BL$ :TBAH$(0,1,0)=BL$ :TBAH$(0,2,0)=BL$ :TBAH$(0,1,1)=BL$
TBAH$(1,1,0)=BL$ :TBAH$(1,0,1)=BL$ :TBAH$(1,1,1)=BL$ :TBAH$(1,1,2)=BL$
TBAH$(2,1,0)=BL$ :TBAH$(2,0,1)=BL$ :TBAH$(2,1,1)=BL$ :TBAH$(2,2,1)=BL$
TBAH$(3,0,0)=BL$ :TBAH$(3,0,1)=BL$ :TBAH$(3,1,1)=BL$ :TBAH$(3,0,2)=BL$
PRINT"HIT BOX BLOCKS DEFINED"
REM -------RETURN-------
LEAVE=FALSE
PROC_Title
REM -------TITLE-LOOP-------
K%=INKEY(0)
IF K%=32 THEN PROC_Start : GOTO """GAME-LOOP"""
IF K%=83 OR K%=115 THEN PROC_Options : GOTO """OPTIONS-LOOP"""
IF K%=76 OR K%=108 THEN PROC_Leave : GOTO """PROGRAM-ENDS"""
GOTO """TITLE-LOOP"""
REM -------OPTIONS-LOOP-------
K%=INKEY(0)
IF K%=81 OR K%=113 THEN PROC_BlockListPrint : PROC_Options
IF K%=87 OR K%=119 THEN PROC_TickRate
IF K%=69 OR K%=101 THEN 
IF K%=76 OR K%=108 THEN PROC_Title : GOTO """TITLE-LOOP"""
GOTO """OPTIONS-LOOP"""
REM -------COLOUR-LOOP-------
K%=INKEY(0)

GOTO """COLOUR-LOOP"""
REM -------GAME-LOOP-------

GOTO """GAME-LOOP"""
REM -------PROGRAM-ENDS-------
END
DEF PROC_BlockColour
FOR SCL=0 TO 17 : PRINTTAB(13,SCL+3)CL$(SCL)

ENDPROC

DEF PROC_BlockListPrint
CLS
PRINTTAB(0,0)OBA$(0) ; :PRINT " BLOCK O"
PRINTTAB(20,0)TBA$(0); :PRINT " BLOCK T"
PRINTTAB(0,5)SBA$(0) ; :PRINT " BLOCK S"
PRINTTAB(20,5)ZBA$(0); :PRINT " BLOCK Z"
PRINTTAB(0,10)LBA$(0); :PRINT " BLOCK L"
PRINTTAB(20,10)JBA$(0); :PRINT " BLOCK J"
PRINTTAB(0,15)IBA$(0); :PRINT " BLOCK I"
PRINTTAB(5,21)"L - TO GO BACK TO MAIN MENU"
ENDPROC

DEF PROC_Start

ENDPROC

DEF PROC_TickRate
CLS
PRINTTAB(13,0)L$Y$"PEDAIR--O" : PRINTTAB(13,1)L$M$"PEDAIR--O"
PRINTTAB(2,3) R$"Difficulty Options for PEDAIR-O:"
PRINTTAB(13,6)"__"
PRINTTAB(2,8)"40 = EASY"
PRINTTAB(2,10)"20 = NORMAL"
PRINTTAB(2,12)"2 = HARD"
PRINTTAB(2,5)" ":INPUT "ENDER SPEED",SPEED%
SETAMSER=SPEED% : IF SPEED%=0 THEN SETAMSER=20
ENDPROC
DEF PROC_Options
CLS
PRINTTAB(13,0)L$Y$"PEDAIR--O" : PRINTTAB(13,1)L$M$"PEDAIR--O"
PRINTTAB(2,3) R$"Options for PEDAIR-O:"
PRINTTAB(2,5)"Q - Show a List Of Shapes"
PRINTTAB(2,7)"W - Change Difficulty/Game Speed: "
PRINTTAB(6,8)"The Speed is:" ; :PRINT SETAMSER
PRINTTAB(2,10)"E - Change Brick Colours: "
PRINTTAB(6,11)"The Colours are: ""Rainbow"""
PRINTTAB(5,21)"L - TO GO BACK TO MAIN MENU"
ENDPROC
DEF PROC_Leave
CLS
PRINTTAB(4,5)"THANK YOU FOR PLAYING MY GAME ^^"
PRINTTAB(9,10)"MAKE BY"; : PRINT R$"Dunvant_Kai"
PRINTTAB(9,20)LBA$(0)
ENDPROC
DEF PROC_Title
CLS
PRINTTAB(9,0) L$Y$"CROESO I PEDAIR-O" : PRINTTAB(9,1)L$M$"CROESO I PEDAIR-O"
PRINTTAB(2,3) R$"Options for PEDAIR-O:" 
PRINTTAB(2,5)"S - Show Game Options"
PRINTTAB(2,7) GL$"Controls:"
PRINTTAB(2,9) "Z - To Move Left"
PRINTTAB(2,11) "X - To Move Right"
PRINTTAB(2,13) "O - To Rotate" : PRINTTAB(2,15) "P - To Drop"
PRINTTAB(2,18) FL$"SPACE" ; :PRINT ST$"- To Start The Game"
PRINTTAB(7,20) "L - To Exit From Game" : PRINTTAB(9,22)"MADE BY" ; : PRINT R$"Dunvant_Kai"
ENDPROC



